'use client'

import { useState, useRef } from 'react'
import { motion, useInView, AnimatePresence } from 'motion/react'
import * as Accordion from '@radix-ui/react-accordion'

const questions = [
  {
    q: 'What is Clarify Data?',
    a: 'Clarify Data is a data verification and business intelligence platform that helps organizations clean and structure raw data, evaluate important claims, analyze current market information, and turn verified information into business intelligence. The platform combines automated data processing, market intelligence, AI claim verification, analytics, and human review for cases requiring additional judgment.',
  },
  {
    q: 'What is data verification?',
    a: 'Data verification is the process of evaluating whether information is accurate, consistent, current, and supported by appropriate evidence. Clarify Data can compare information against verified datasets, market intelligence, historical information, trusted sources, and relevant business benchmarks.',
  },
  {
    q: 'What is the difference between data validation and data verification?',
    a: 'Data validation generally checks whether data meets required rules, formats, structures, or constraints. Data verification focuses on whether the information itself is supported, accurate, current, and reliable. Clarify Data uses both concepts as part of a broader information-quality workflow.',
  },
  {
    q: 'How is Clarify Data different from asking AI to fact-check itself?',
    a: 'Clarify Data is designed to evaluate AI-generated claims against external information and evidence rather than simply asking another model to generate a second answer. The system can consider market data, historical information, verified datasets, trusted references, confidence indicators, and human review.',
  },
  {
    q: 'Which AI platforms can Clarify Data verify?',
    a: 'Clarify Data can evaluate submitted content generated by platforms such as ChatGPT, Gemini, Claude, Grok, DeepSeek, and other AI systems. Verification focuses on the claims contained in the content rather than the AI platform that generated them.',
  },
  {
    q: 'What is the Clarify Data Trust Index?',
    a: 'The Trust Index communicates how strongly the available evidence supports a claim, dataset, or report. It can consider factors such as evidence quality, information freshness, source consistency, industry relevance, uncertainty, and human verification.',
  },
  {
    q: 'What is the Verified Data Index?',
    a: 'The Verified Data Index communicates the level and type of confirmation achieved during the verification process. It helps users distinguish between fully verified, partially verified, conflicting, outdated, unverified, and human-reviewed information.',
  },
  {
    q: 'How does Data Sort work?',
    a: 'Users upload data through supported formats such as CSV, Excel, documents, or APIs. Clarify Data identifies the structure, categories, missing information, duplicates, and formatting inconsistencies and helps transform the information into a cleaner and more structured dataset.',
  },
  {
    q: 'What does Clarify Data provide for business intelligence?',
    a: 'Business intelligence outputs can include performance analysis, market comparisons, industry trends, risks, opportunities, forecasts, performance gaps, verification results, supporting evidence, and analyst recommendations.',
  },
  {
    q: 'When does human verification happen?',
    a: 'Human review can be used when available evidence is conflicting or incomplete, when confidence is low, when industry context is important, or when the information could affect a high-impact decision. Users may also request additional expert review where available.',
  },
  {
    q: 'What happens to private business data?',
    a: 'Private information is processed according to the privacy, access, storage, and retention terms applicable to the customer\'s account. The exact production policy is detailed in the Privacy Policy and Data Processing Agreement.',
  },
  {
    q: 'Which industries does Clarify Data support?',
    a: 'The initial industry focus includes E-commerce and social media, Healthcare, Logistics and supply chain, and Education. Industry-specific verification allows relevant data, terminology, market conditions, and expert context to be considered.',
  },
  {
    q: 'How do I get started?',
    a: 'Book a demo and bring a real business question, AI-generated document, report, or dataset. The Clarify Data team can demonstrate how the platform processes and verifies information using a realistic workflow.',
  },
]

export default function Faq() {
  const [open, setOpen] = useState<string>('')
  const ref = useRef<HTMLElement>(null)
  const inView = useInView(ref as React.RefObject<Element>, { once: true, margin: '-8%' })

  return (
    <section
      ref={ref}
      id="faq"
      className="section-pad relative overflow-hidden"
      style={{ background: 'rgb(10,10,10)' }}
    >
      <div className="section-inner relative z-10">
        <div className="grid md:grid-cols-[2fr_3fr] gap-8 md:gap-16">
          {/* Left column */}
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5 }}
          >
            <span className="eyebrow-pill mb-6 inline-block">FAQ</span>
            <h2
              className="mb-4 text-[26px] md:text-[40px]"
              style={{ fontWeight: 600, letterSpacing: '-1.2px', lineHeight: '1.2', color: 'rgb(250,250,250)' }}
            >
              Frequently Asked Questions
            </h2>
            <p style={{ fontSize: '16px', color: 'rgba(250,250,250,0.6)', lineHeight: '24px' }}>
              Have more questions about integration, data security, or custom enterprise deployments? Reach out to our team.
            </p>
          </motion.div>

          {/* Right column: Accordion */}
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            <Accordion.Root
              type="single"
              collapsible
              value={open}
              onValueChange={setOpen}
              className="flex flex-col"
            >
              {questions.map((item, i) => (
                <Accordion.Item
                  key={item.q}
                  value={`item-${i}`}
                  className="border-b"
                  style={{ borderColor: 'rgba(250,250,250,0.08)' }}
                >
                  <Accordion.Trigger
                    className="flex w-full items-center justify-between gap-6 py-5 text-left outline-none cursor-pointer group"
                  >
                    <span
                      className="text-[16px] font-medium transition-colors duration-200"
                      style={{
                        color: open === `item-${i}` ? 'rgb(250,250,250)' : 'rgba(250,250,250,0.8)',
                        letterSpacing: '-0.3px',
                      }}
                    >
                      {item.q}
                    </span>
                    <span
                      className="shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-[14px] transition-all duration-200"
                      style={{
                        background: open === `item-${i}` ? 'rgba(250,250,250,0.1)' : 'rgba(250,250,250,0.07)',
                        color: open === `item-${i}` ? 'rgb(250,250,250)' : 'rgba(250,250,250,0.4)',
                        transform: open === `item-${i}` ? 'rotate(45deg)' : 'none',
                      }}
                    >
                      +
                    </span>
                  </Accordion.Trigger>
                  <Accordion.Content className="overflow-hidden">
                    <AnimatePresence>
                      {open === `item-${i}` && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.3, ease: [0.44, 0, 0.56, 1] }}
                        >
                          <p
                            className="pb-5 text-[15px] leading-6"
                            style={{ color: 'rgba(250,250,250,0.65)' }}
                          >
                            {item.a}
                          </p>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </Accordion.Content>
                </Accordion.Item>
              ))}
              <div className="border-b" style={{ borderColor: 'rgba(250,250,250,0.08)' }} />
            </Accordion.Root>
          </motion.div>
        </div>
      </div>
    </section>
  )
}
